preload = /home/tommlyjumah/Downloads/pics-svg/hyper.png
wallpaper = /home/tommlyjumah/Downloads/pics-svg/hyper.png

#wallpaper {
    #path = /home/tommlyjumah/Downloads/wallpapers/
    #fit_mode = cover
   # timeout = 7200
  #order = random
 #   recursive = true
#}
