general {
    before_sleep_cmd = playerctl pause --all-players
    after_sleep_cmd = hyprctl dispatch dpms on && pkill hyprlock; sleep 0.2; hyprlock &
}

# Screen off after 3min idle
listener {
    timeout = 180
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock after 5min idle
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# Warn 30s before battery hibernate
listener {
    timeout = 870
    on-timeout = notify-send -u critical "Hibernating in 30s" "Move mouse/press key to cancel"
}

# Hibernate on battery after 15min idle
#listener {
  #  timeout = 900
 #on-timeout = [[ $(cat /sys/class/power_supply/BAT*/status) == "Discharging" ]] && systemctl hibernate
#}

listener {
    timeout = 900
    on-timeout = [[ $(cat /sys/class/power_supply/AC/online) == "0" ]] && systemctl hibernate
}

# Warn 30s before AC hibernate
listener {
    timeout = 1470
    on-timeout = notify-send -u critical "Hibernating in 30s" "Move mouse/press key to cancel"
}

# Hibernate on AC after 25min idle
listener {
    timeout = 1500
    on-timeout = [[ $(cat /sys/class/power_supply/AC/online) == "1" ]] && systemctl hibernate
}
#listener {
#    timeout = 1500
#    on-timeout = [[ $(cat /sys/class/power_supply/ADP*/online) == "1" ]] && systemctl hibernate
#}
